### ISSUE TITLE
Camera troubleshooting

### ISSUE THREAD

**Issue by leighghunt** [venari/timelapse#18]
Logs:

```
1 packets transmitted, 1 received, 0% packet loss, time 0ms                             
rtt min/avg/max/mdev = 55.381/55.381/55.381/0.000 ms                                    
+++ date
++ echo Wed Feb 9 16:24:59 NZDT 2022
++ echo 'network interface either up or we gave up'                                     
++ echo
++ date
++ /usr/bin/python3 coreScript.py
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'                  
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 129, in _control_callback
    "Received unexpected camera control callback event, 0x%08x" % buf[0].cmd)           
picamera.exc.PiCameraRuntimeError: Received unexpected camera control callback event, 0x4f525245
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'                  
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 129, in _control_callback
    "Received unexpected camera control callback event, 0x%08x" % buf[0].cmd)           
picamera.exc.PiCameraRuntimeError: Received unexpected camera control callback event, 0x4f525245
Shutdown scheduled for Wed 2022-02-09 16:27:10 NZDT, use 'shutdown -c' to cancel.       
+++ date
++ echo Wed Feb 9 16:26:10 NZDT 2022
++ echo 'startup script finished'

```

**Comment by leighghunt** [comment]
Sometimes seems to get hung up when battery goes flat, and only way to reset it was to disconnect battery and power.
