### ISSUE TITLE
Errors encountered running on Pi Zero W (1.1) without camera attached

### ISSUE THREAD

**Issue by leighghunt** [venari/timelapse#23]
Need to fail more gracefully from this situation - ends up with pi powering off with failsafe after 2min30, and not being set to wake up.

```
pi@timelapse-pi-2:~/dev/timelapse/scripts$ python3 coreScript.py
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --verbose option to see the details of our search for an access method.
2022-04-05 02:51:59.238670 Setting failsafe power off for 2 minutes 30 seconds from now.
{'batteryPercent': 15, 'temperatureC': 45, 'diskSpaceFree': 11, 'uptimeSeconds': 63, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3953, 'batteryCurrent': -1134, 'ioVoltage': 5070, 'ioCurrent': 174}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-05 02:52:00.356392 Logged to API.
2022-04-05 02:52:00.377430 warming up... waiting 30s
{'batteryPercent': 16, 'temperatureC': 45, 'diskSpaceFree': 11, 'uptimeSeconds': 94, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3951, 'batteryCurrent': -1119, 'ioVoltage': 5070, 'ioCurrent': 213}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-05 02:52:31.423089 Logged to API.
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 456, in _init_camera
    self._camera = mo.MMALCamera()
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/mmalobj.py", line 2279, in __init__
    super(MMALCamera, self).__init__()
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/mmalobj.py", line 633, in __init__
    prefix="Failed to create MMAL component %s" % self.component_type)
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.ril.camera': Out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coreScript.py", line 185, in <module>
    savePhoto()
  File "coreScript.py", line 79, in savePhoto
    with PiCamera() as camera:
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 431, in __init__
    self._init_camera(camera_num, stereo_mode, stereo_decimate)
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 460, in _init_camera
    "Camera is not enabled. Try running 'sudo raspi-config' "
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coreScript.py", line 190, in <module>
    print(str(datetime.datetime.now()) + e)
TypeError: can only concatenate str (not "PiCameraError") to str
1 pi@timelapse-pi-2:~/dev/timelapse/scripts$
```

**Comment by leighghunt** [comment]
Note - even after enabling camera interface - but still having no camera connected, get the same error:

```
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --verbose option to see the details of our search for an access method.
2022-04-05 03:04:50.030330 Setting failsafe power off for 2 minutes 30 seconds from now.
{'batteryPercent': 18, 'temperatureC': 47, 'diskSpaceFree': 11, 'uptimeSeconds': 137, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3978, 'batteryCurrent': -1191, 'ioVoltage': 5070, 'ioCurrent': 201}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-05 03:04:50.866536 Logged to API.
2022-04-05 03:04:50.885609 warming up... waiting 30s
{'batteryPercent': 18, 'temperatureC': 48, 'diskSpaceFree': 11, 'uptimeSeconds': 167, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3979, 'batteryCurrent': -1198, 'ioVoltage': 5081, 'ioCurrent': 168}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-05 03:05:21.743166 Logged to API.
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 456, in _init_camera
    self._camera = mo.MMALCamera()
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/mmalobj.py", line 2279, in __init__
    super(MMALCamera, self).__init__()
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/mmalobj.py", line 633, in __init__
    prefix="Failed to create MMAL component %s" % self.component_type)
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.ril.camera': Out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coreScript.py", line 185, in <module>
    savePhoto()
  File "coreScript.py", line 79, in savePhoto
    with PiCamera() as camera:
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 431, in __init__
    self._init_camera(camera_num, stereo_mode, stereo_decimate)
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/camera.py", line 460, in _init_camera
    "Camera is not enabled. Try running 'sudo raspi-config' "
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coreScript.py", line 190, in <module>
    print(str(datetime.datetime.now()) + e)
TypeError: can only concatenate str (not "PiCameraError") to str
```

**Comment by leighghunt** [comment]
After - getting the following - shutdown scheduled - but perhaps wrong timezone?

```
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --verbose option to see the details of our search for an access method.
2022-04-05 03:07:16.802291 Setting failsafe power off for 2 minutes 30 seconds from now.
{'batteryPercent': 18, 'temperatureC': 48, 'diskSpaceFree': 11, 'uptimeSeconds': 283, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3981, 'batteryCurrent': -1191, 'ioVoltage': 5070, 'ioCurrent': 227}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-05 03:07:17.576912 Logged to API.
2022-04-05 03:07:17.597217 warming up... waiting 30s
{'batteryPercent': 19, 'temperatureC': 48, 'diskSpaceFree': 11, 'uptimeSeconds': 314, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3982, 'batteryCurrent': -1198, 'ioVoltage': 5082, 'ioCurrent': 109}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-05 03:07:48.346559 Logged to API.
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
2022-04-05 03:07:48.469855Catastrophic failure
2022-04-05 03:07:48.473644 scheduling shutdown
Alarm set for {'data': {'second': 0, 'minute_period': 10, 'hour': 18, 'day': 'EVERY_DAY'}, 'error': 'NO_ERROR'}
2022-04-05 03:07:48.691718 Shutting down...

Broadcast message from root@timelapse-pi-2 on pts/1 (Tue 2022-04-05 03:07:48 BST):
```

Fixed in 0606f5f, and changing timezone.
```
sudo timedatectl set-timezone Pacific/Auckland
```

**Comment by leighghunt** [comment]
Actually still seems to be having probs, and looks like it's not managed to update the wakeup alarm, so is carrying on waking up every 10 minutes.

UploadTelemetry log:

```
Wed  6 Apr 21:45:01 NZST 2022
A
67
35
11
279
{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3921, 'batteryCurrent': 402, 'ioVoltage': 5072, 'ioCurrent': 150}
00000000dcc1f9e4
Z
{'batteryPercent': 67, 'temperatureC': 35, 'diskSpaceFree': 11, 'uptimeSeconds': 279, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3921, 'batteryCurrent': 402, 'ioVoltage': 5067, 'ioCurrent': 187}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-06 21:45:04.995990 Logged to API.

Wed  6 Apr 21:46:01 NZST 2022
A
'data'

Wed  6 Apr 21:47:02 NZST 2022
A
'data'

Wed  6 Apr 21:48:01 NZST 2022
A
'data'

Wed  6 Apr 21:49:01 NZST 2022
A
'data'

Wed  6 Apr 21:51:29 NZST 2022
A
67
36
11
67
{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3913, 'batteryCurrent': 454, 'ioVoltage': 5067, 'ioCurrent': 191}
00000000dcc1f9e4
Z
{'batteryPercent': 67, 'temperatureC': 36, 'diskSpaceFree': 11, 'uptimeSeconds': 67, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3913, 'batteryCurrent': 454, 'ioVoltage': 5062, 'ioCurrent': 191}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-06 21:51:33.280898 Logged to API.

Wed  6 Apr 21:51:33 NZST 2022
A
67
35
11
71
{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3916, 'batteryCurrent': 432, 'ioVoltage': 5067, 'ioCurrent': 236}
00000000dcc1f9e4
Z
{'batteryPercent': 67, 'temperatureC': 35, 'diskSpaceFree': 11, 'uptimeSeconds': 71, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3916, 'batteryCurrent': 432, 'ioVoltage': 5067, 'ioCurrent': 236}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-06 21:51:36.806380 Logged to API.

Wed  6 Apr 21:52:01 NZST 2022
A
'data'

Wed  6 Apr 21:53:01 NZST 2022
A
'data'

Wed  6 Apr 21:54:01 NZST 2022
A
'data'

Wed  6 Apr 21:55:02 NZST 2022
A
'data'
```


coreScipt log:

```
Wed  6 Apr 19:52:06 NZST 2022
2022-04-06 19:52:11.123483 Setting failsafe power off for 2 minutes 30 seconds from now.
{'batteryPercent': 73, 'temperatureC': 31, 'diskSpaceFree': 11, 'uptimeSeconds': 43, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3941, 'batteryCurrent': 395, 'ioVoltage': 5061, 'ioCurrent': 210}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-06 19:52:11.975915 Logged to API.
2022-04-06 19:52:11.992690 warming up... waiting 30s
{'batteryPercent': 73, 'temperatureC': 32, 'diskSpaceFree': 11, 'uptimeSeconds': 74, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'NORMAL', 'powerInput': 'NOT_PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 3957, 'batteryCurrent': 278, 'ioVoltage': 5079, 'ioCurrent': -321}", 'SerialNumber': '00000000dcc1f9e4'}
<Response [200]>
2022-04-06 20:01:25.954159 Logged to API.
2022-04-06 20:01:26.060494 Catastrophic failure
2022-04-06 20:01:26.060702 scheduling shutdown
Alarm set for {'data': {'second': 0, 'minute_period': 10, 'hour': 'EVERY_HOUR', 'day': 'EVERY_DAY'}, 'error': 'NO_ERROR'}
2022-04-06 20:01:26.271863 Shutting down...
2022-04-06 20:01:26.426992 Power off scheduled for 30s from now
Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.

Wed  6 Apr 20:01:52 NZST 2022
2022-04-06 20:01:57.142715 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 20:01:57.148388 Catastrophic failure
2022-04-06 20:01:57.148586 scheduling shutdown
Cannot set alarm


Wed  6 Apr 20:19:21 NZST 2022
2022-04-06 20:19:25.969977 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 20:19:25.975631 Catastrophic failure
2022-04-06 20:19:25.975834 scheduling shutdown
Cannot set alarm


Wed  6 Apr 20:29:35 NZST 2022
2022-04-06 20:29:39.922184 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 20:29:39.928078 Catastrophic failure
2022-04-06 20:29:39.928278 scheduling shutdown
Cannot set alarm


Wed  6 Apr 20:39:36 NZST 2022
2022-04-06 20:39:40.323714 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 20:39:40.329403 Catastrophic failure
2022-04-06 20:39:40.329606 scheduling shutdown
Cannot set alarm


Wed  6 Apr 20:49:34 NZST 2022
2022-04-06 20:49:39.206604 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 20:49:39.212189 Catastrophic failure
2022-04-06 20:49:39.212390 scheduling shutdown
Cannot set alarm


Wed  6 Apr 20:59:34 NZST 2022
2022-04-06 20:59:39.359689 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 20:59:39.365281 Catastrophic failure
2022-04-06 20:59:39.365483 scheduling shutdown
Cannot set alarm


Wed  6 Apr 21:09:34 NZST 2022
2022-04-06 21:09:39.234532 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 21:09:39.240095 Catastrophic failure
2022-04-06 21:09:39.240298 scheduling shutdown
Cannot set alarm


Wed  6 Apr 21:19:34 NZST 2022
2022-04-06 21:19:38.714463 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 21:19:38.720084 Catastrophic failure
2022-04-06 21:19:38.720287 scheduling shutdown
Cannot set alarm


Wed  6 Apr 21:29:36 NZST 2022
2022-04-06 21:29:40.863463 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 21:29:40.869094 Catastrophic failure
2022-04-06 21:29:40.869297 scheduling shutdown
Cannot set alarm


Wed  6 Apr 21:39:35 NZST 2022
2022-04-06 21:39:40.334087 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 21:39:40.339655 Catastrophic failure
2022-04-06 21:39:40.339852 scheduling shutdown
Cannot set alarm


Wed  6 Apr 21:49:36 NZST 2022
2022-04-06 21:49:41.594098 Setting failsafe power off for 2 minutes 30 seconds from now.
2022-04-06 21:49:41.599733 Catastrophic failure
2022-04-06 21:49:41.599935 scheduling shutdown
Cannot set alarm
```

**Comment by leighghunt** [comment]
`Cannot set alarm`, and other communication issues with this Pi/PiJuice combination.

```
pi@timelapse-pi-2:~$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pijuice
^[[Apj = pijuice.PiJuice(1, 0x14)
>>> print (pj.status.GetChargeLevel())
{'error': 'COMMUNICATION_ERROR'}
>>> print (pj.status.GetChargeLevel()['data'])
76
```

**Comment by leighghunt** [comment]
Possibly linked issue to investigate: https://github.com/PiSupply/PiJuice/issues/610

**Comment by leighghunt** [comment]
Also possibly relevant: https://github.com/raspberrypi/linux/issues/3064

**Comment by leighghunt** [comment]
Think it might have been resolved by updating the ubuntu install.

```
sudo apt-get update
sudo apt-get upgrade
```
