### ISSUE TITLE
STORAGE_CONNECTION_STRING being unset causes imagery to be lost

### ISSUE THREAD

**Issue by leighghunt** [venari/timelapse#45]
Whilst deploying I inadvertently cleared STORAGE_CONNECTION_STRING - imagery was sent to the API, and not stored, yet Pi thought it was.

**Comment by leighghunt** [comment]
Example logging:

```
2023-01-25T04:48:06.158160807Z fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]

2023-01-25T04:48:06.158204108Z       An unhandled exception has occurred while executing the request.

2023-01-25T04:48:06.158211108Z       System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')

2023-01-25T04:48:06.159545512Z          at Azure.Storage.StorageConnectionString.Parse(String connectionString)

2023-01-25T04:48:06.159562912Z          at Azure.Storage.Blobs.BlobContainerClient..ctor(String connectionString, String blobContainerName, BlobClientOptions options)

2023-01-25T04:48:06.159577612Z          at timelapse.api.Helpers.StorageHelper..ctor(IConfiguration configuration, ILogger logger, IMemoryCache memoryCache) in /home/runner/work/timelapse/timelapse/timelapse.api/Helpers/StorageHelper.cs:line 33

2023-01-25T04:48:06.159583312Z          at lambda_method194(Closure , IServiceProvider , Object[] )

2023-01-25T04:48:06.159588012Z          at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)

2023-01-25T04:48:06.159593712Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

2023-01-25T04:48:06.159598912Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

2023-01-25T04:48:06.159603712Z       --- End of stack trace from previous location ---

2023-01-25T04:48:06.159608112Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(Res
ourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2023-01-25T04:48:06.159613112Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

2023-01-25T04:48:06.159908713Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

2023-01-25T04:48:06.159921613Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()

2023-01-25T04:48:06.165812532Z       --- End of stack trace from previous location ---

2023-01-25T04:48:06.165826332Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

2023-01-25T04:48:06.166443034Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

2023-01-25T04:48:06.166457134Z          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

2023-01-25T04:48:06.166462434Z          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)

2023-01-25T04:48:06.166466534Z          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

2023-01-25T04:48:06.166470834Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

2023-01-25T04:48:06.166474934Z          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


```

**Comment by leighghunt** [comment]
Suspect a combination of that request erroring, and the page not being authenticated meant it got bounced to the login page, which technically was a 200 result.


Last successfully saved images:
```
2023-01-25 17:10:43,351 DEBUG: Starting new HTTPS connection (1): timelapse-dev.azurewebsites.net:443
2023-01-25 17:10:44,004 DEBUG: https://timelapse-dev.azurewebsites.net:443 "POST /api/Telemetry HTTP/1.1" 200 None
2023-01-25 17:10:44,011 DEBUG: <Response [200]>
2023-01-25 17:10:44,012 DEBUG: Telemetry uploaded successfully
2023-01-25 17:10:44,013 DEBUG: Logged to API.
2023-01-25 17:10:44,033 INFO:  uploading ../output/images/pending/2023-01-25_171040.jpg
2023-01-25 17:10:44,034 DEBUG: imageTimestamp:
2023-01-25 17:10:44,035 DEBUG: 2023-01-25 17:10:40
2023-01-25 17:10:44,036 DEBUG: data:
2023-01-25 17:10:44,036 DEBUG: {'SerialNumber': '00000000f3c2ec94', 'Timestamp': '2023-01-25T17:10:40+13:00'}
2023-01-25 17:10:44,037 DEBUG: Posting image to API...
2023-01-25 17:10:44,077 DEBUG: Starting new HTTPS connection (1): timelapse-dev.azurewebsites.net:443
2023-01-25 17:10:46,134 DEBUG: https://timelapse-dev.azurewebsites.net:443 "POST /api/Image HTTP/1.1" 200 None
2023-01-25 17:10:46,152 DEBUG: Response code: 200
2023-01-25 17:10:46,152 DEBUG: Image uploaded successfully
2023-01-25 17:10:46,153 DEBUG: Response text:
2023-01-25 17:10:46,154 DEBUG: {
    "timestamp": "2023-01-25T04:10:40Z",
    "blobUri": "https://venaritimelapse.blob.core.windows.net/timelapse/1_2023-01-25_171040.jpg",
2023-01-25 17:10:51,342 DEBUG: beginning capture
2023-01-25 17:10:51,363 DEBUG: warming up camera...
2023-01-25 17:10:56,264 INFO:  deleting old uploaded image ../output/images/uploaded/2023-01-24_171042.jpg
2023-01-25 17:10:56,369 DEBUG: ready
2023-01-25 17:10:56,572 INFO:  deleting old uploaded telemetry ../output/telemetry/uploaded/2023-01-24_171043.json
2023-01-25 17:10:56,646 INFO:  uploading ../output/images/pending/2023-01-25_171056.jpg
2023-01-25 17:10:56,647 DEBUG: imageTimestamp:
2023-01-25 17:10:56,647 DEBUG: 2023-01-25 17:10:56
2023-01-25 17:10:56,648 ERROR: Empty file - deleting
2023-01-25 17:10:56,945 DEBUG: image saved
2023-01-25 17:10:57,001 DEBUG: telemetry saved
2023-01-25 17:10:57,002 DEBUG: scheduleShutdown
2023-01-25 17:10:57,003 DEBUG: skipping shutdown scheduling because of config.json
2023-01-25 17:11:06,751 INFO:  deleting old uploaded image ../output/images/uploaded/2023-01-24_171058.jpg
2023-01-25 17:11:06,943 INFO:  deleting old uploaded telemetry ../output/telemetry/uploaded/2023-01-24_171059.json
2023-01-25 17:11:07,126 INFO:  uploading ../output/telemetry/pending/2023-01-25_171057.json
2023-01-25 17:11:07,126 DEBUG: telemetryTimestamp:
2023-01-25 17:11:07,127 DEBUG: 2023-01-25 17:10:57
2023-01-25 17:11:07,127 DEBUG: {'batteryPercent': 95, 'temperatureC': 54, 'diskSpaceFree': 40, 'pendingImages': 0, 'uploadedImages': 5047, 'pendingTelemetry': 0, 'uploadedTelemetry': 5378, 'uptimeSeconds': 343623, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 4140, 'batteryCurrent': 4176, 'ioVoltage': 5023, 'ioCurrent': 643}", 'SerialNumber': '00000000f3c2ec94', 'Timestamp': '2023-01-25T17:10:57+13:00'}
2023-01-25 17:11:07,133 DEBUG: Starting new HTTPS connection (1): timelapse-dev.azurewebsites.net:443
2023-01-25 17:11:07,171 DEBUG: beginning capture
2023-01-25 17:11:07,193 DEBUG: warming up camera...
2023-01-25 17:11:07,758 DEBUG: https://timelapse-dev.azurewebsites.net:443 "POST /api/Telemetry HTTP/1.1" 200 None
2023-01-25 17:11:07,763 DEBUG: <Response [200]>
2023-01-25 17:11:07,763 DEBUG: Telemetry uploaded successfully
2023-01-25 17:11:07,764 DEBUG: Logged to API.
2023-01-25 17:11:12,199 DEBUG: ready
2023-01-25 17:11:12,938 DEBUG: image saved
2023-01-25 17:11:13,015 DEBUG: telemetry saved
2023-01-25 17:11:13,016 DEBUG: scheduleShutdown
2023-01-25 17:11:13,017 DEBUG: skipping shutdown scheduling because of config.json
2023-01-25 17:11:17,912 INFO:  deleting old uploaded image ../output/images/uploaded/2023-01-24_171114.jpg
2023-01-25 17:11:18,136 INFO:  deleting old uploaded telemetry ../output/telemetry/uploaded/2023-01-24_171115.json
2023-01-25 17:11:18,247 INFO:  uploading ../output/telemetry/pending/2023-01-25_171113.json
2023-01-25 17:11:18,248 DEBUG: telemetryTimestamp:
2023-01-25 17:11:18,248 DEBUG: 2023-01-25 17:11:13
2023-01-25 17:11:18,249 DEBUG: {'batteryPercent': 95, 'temperatureC': 54, 'diskSpaceFree': 40, 'pendingImages': 1, 'uploadedImages': 5046, 'pendingTelemetry': 0, 'uploadedTelemetry': 5378, 'uptimeSeconds': 343639, 'status': "{'status': {'isFault': False, 'isButton': False, 'battery': 'CHARGING_FROM_IN', 'powerInput': 'PRESENT', 'powerInput5vIo': 'NOT_PRESENT'}, 'batteryVoltage': 4140, 'batteryCurrent': 4176, 'ioVoltage': 5030, 'ioCurrent': 517}", 'SerialNumber': '00000000f3c2ec94', 'Timestamp': '2023-01-25T17:11:13+13:00'}                                                                                                                
2023-01-25 17:11:18,255 DEBUG: Starting new HTTPS connection (1): timelapse-dev.azurewebsites.net:443
2023-01-25 17:11:23,206 DEBUG: beginning capture          
2023-01-25 17:11:23,232 DEBUG: warming up camera...
2023-01-25 17:11:28,238 DEBUG: ready            
2023-01-25 17:11:28,980 DEBUG: image saved                                             
2023-01-25 17:11:29,058 DEBUG: telemetry saved
2023-01-25 17:11:29,058 DEBUG: scheduleShutdown   
2023-01-25 17:11:29,059 DEBUG: skipping shutdown scheduling because of config.json
2023-01-25 17:11:38,528 DEBUG: https://timelapse-dev.azurewebsites.net:443 "POST /api/Telemetry HTTP/1.1" 200 None
2023-01-25 17:11:38,535 DEBUG: <Response [200]>       
2023-01-25 17:11:38,536 DEBUG: Telemetry uploaded successfully
```

First failure:

```
2023-01-25 17:11:38,537 DEBUG: Logged to API.
2023-01-25 17:11:38,557 INFO:  uploading ../output/images/pending/2023-01-25_171128.jpg
2023-01-25 17:11:38,559 DEBUG: imageTimestamp:
2023-01-25 17:11:38,559 DEBUG: 2023-01-25 17:11:28
2023-01-25 17:11:38,560 DEBUG: data:
2023-01-25 17:11:38,560 DEBUG: {'SerialNumber': '00000000f3c2ec94', 'Timestamp': '2023-01-25T17:11:28+13:00'}
2023-01-25 17:11:38,561 DEBUG: Posting image to API...
2023-01-25 17:11:38,602 DEBUG: Starting new HTTPS connection (1): timelapse-dev.azurewebsites.net:443
2023-01-25 17:11:39,209 DEBUG: beginning capture
2023-01-25 17:11:39,227 DEBUG: warming up camera...
2023-01-25 17:11:40,336 DEBUG: https://timelapse-dev.azurewebsites.net:443 "POST /api/Image HTTP/1.1" 302 0
2023-01-25 17:11:42,241 DEBUG: https://timelapse-dev.azurewebsites.net:443 "GET /Identity/Account/Login?ReturnUrl=%2FError HTTP/1.1" 200 None
2023-01-25 17:11:42,261 DEBUG: Response code: 200
2023-01-25 17:11:42,261 DEBUG: Image uploaded successfully
2023-01-25 17:11:42,262 DEBUG: Response text:
2023-01-25 17:11:42,266 DEBUG: <!DOCTYPE html>^M
2023-01-25 17:11:42,267 INFO:  uploading ../output/images/pending/2023-01-25_171112.jpg
2023-01-25 17:11:42,268 DEBUG: imageTimestamp:
2023-01-25 17:11:42,269 DEBUG: 2023-01-25 17:11:12
2023-01-25 17:11:42,270 DEBUG: data:
2023-01-25 17:11:42,270 DEBUG: {'SerialNumber': '00000000f3c2ec94', 'Timestamp': '2023-01-25T17:11:12+13:00'}
2023-01-25 17:11:42,271 DEBUG: Posting image to API...
2023-01-25 17:11:42,313 DEBUG: Starting new HTTPS connection (1): timelapse-dev.azurewebsites.net:443
2023-01-25 17:11:44,200 DEBUG: https://timelapse-dev.azurewebsites.net:443 "POST /api/Image HTTP/1.1" 302 0
2023-01-25 17:11:44,233 DEBUG: ready

```
